AWSTemplateFormatVersion: 2010-09-09
Description: First tempate to demonstrate Lambda function using Cloudformation

Parameters:
  RegionToDeploy:
    Type: String
    Description: The AWS region where the resource needs to be deployed.
  DeployType:
    Type: String
    Description: Target environment where the code will be deployed e.g 'dev', 'staging', 'prod' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.


Resources:
  
  StepFunctionAccessEnableRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/ProjAdminsPermBoundaryv2'
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: "Allow StepFunctions to enable accessing Lambda service"
      Policies:
        - PolicyName: Proj-Policy-inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'cloudformation:*'
                Resource: '*'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      RoleName: !Sub 'Proj-StepFunctionAccessEnable-${DeployType}'
  
  LambdaServiceAccessEnableRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/ProjAdminsPermBoundaryv2'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: "Allow Lambda service to handle different AWS Services"
      Policies:
        - PolicyName: Proj-Policy-inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:Describe*'
                  - 'lambda:*'
                  - 'ec2:*'
                  - 'sqs:*'
                  - 'dynamodb:*'
                  - 's3:*'
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      RoleName: !Sub 'Proj-LambdaServiceAccessEnableRole-${DeployType}'

  StateMachineParallelClusterEngine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      Role: !GetAtt 'StepFunctionAccessEnableRole.Arn'
      DefinitionString: !Sub |
        {
          "StartAt": "get suitable instance type",
          "States": {
            "get suitable instance type": {
              "Type": "Task",
              "Resource": "${LambdaFunctionInstanceSelection.Arn}",
              "InputPath": "$",
              "OutputPath": "$",
              "ResultPath": "$.EFS.instance_type",
              "TimeoutSeconds": 60,
              "Next": "prepare pcluster config file",
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.Unknown",
                    "Lambda.TooManyRequestsException",
                    "Lambda.SdkClientException",
                    "States.DataLimitExceeded"
                  ],
                  "IntervalSeconds": 10,
                  "MaxAttempts": 10,
                  "BackoffRate": 3
                }
              ]
            },
            "prepare pcluster config file": {
              "Type": "Task",
              "Resource": "${LambdaFunctionPclusterConfigInstantiate.Arn}",
              "InputPath": "$",
              "OutputPath": "$",
              "ResultPath": "$",
              "TimeoutSeconds": 60,
              "Next": "invoke pcluster create",
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.Unknown",
                    "Lambda.TooManyRequestsException",
                    "Lambda.SdkClientException",
                    "States.DataLimitExceeded"
                  ],
                  "IntervalSeconds": 10,
                  "MaxAttempts": 10,
                  "BackoffRate": 3
                }
              ]
            },
            "invoke pcluster create": {
              "Type": "Task",
              "Resource": "${LambdaFunctionClusterCreation.Arn}",
              "InputPath": "$",
              "OutputPath": "$",
              "ResultPath": "$.pcluster_create",
              "TimeoutSeconds": 60,
              "Next": "WaitForSomeTime",
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.Unknown",
                    "Lambda.TooManyRequestsException",
                    "Lambda.SdkClientException",
                    "States.DataLimitExceeded"
                  ],
                  "IntervalSeconds": 10,
                  "MaxAttempts": 10,
                  "BackoffRate": 3
                }
              ]
            },
            "WaitForSomeTime": {
              "Type": "Wait",
              "InputPath": "$",
              "OutputPath": "$",
              "Seconds": 60,
              "Next": "check pcluster status"
            },
            "WaitForMoreTime": {
              "Type": "Wait",
              "InputPath": "$",
              "OutputPath": "$",
              "Seconds": 120,
              "Next": "invoke pcluster create"
            },
            "check pcluster status": {
              "Type": "Task",
              "Resource": "${LambdaFunctionClusterCreationStatus.Arn}",
              "ResultPath": "$.pcluster.status",
              "TimeoutSeconds": 300,
              "Next": "is pcluster ready",
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.Unknown",
                    "Lambda.TooManyRequestsException",
                    "Lambda.SdkClientException",
                    "States.DataLimitExceeded"
                  ],
                  "IntervalSeconds": 10,
                  "MaxAttempts": 10,
                  "BackoffRate": 3
                }
              ]
            },
            "is pcluster ready": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.pcluster.status",
                  "StringEquals": "CREATE_IN_PROGRESS",
                  "Next": "Power nap of 300 secs"
                },
                {
                  "Variable": "$.pcluster.status",
                  "StringEquals": "NOT_FOUND",
                  "Next": "WaitForMoreTime"
                },
                {
                  "Variable": "$.pcluster.status",
                  "StringEquals": "ROLLBACK_COMPLETE",
                  "Next": "log the details into db"
                },
                {
                  "Variable": "$.pcluster.status",
                  "StringEquals": "ROLLBACK_IN_PROGRESS",
                  "Next": "log the details into db"
                },
                {
                  "Variable": "$.pcluster.status",
                  "StringEquals": "CREATE_COMPLETE",
                  "Next": "pcluster created"
                }
              ]
            },
            "Power nap of 300 secs": {
              "Type": "Wait",
              "InputPath": "$",
              "OutputPath": "$",
              "Seconds": 300,
              "Next": "check pcluster status"
            },
            "pcluster created": {
              "Type": "Pass",
              "Next": "get pcluster master instance details"
            },
            "get pcluster master instance details": {
              "Type": "Task",
              "Resource": "${LambdaFunctionMasterInstanceDetails.Arn}",
              "InputPath": "$",
              "OutputPath": "$",
              "ResultPath": "$",
              "TimeoutSeconds": 60,
              "Next": "log the details into db",
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.Unknown",
                    "Lambda.TooManyRequestsException",
                    "Lambda.SdkClientException",
                    "States.DataLimitExceeded"
                  ],
                  "IntervalSeconds": 10,
                  "MaxAttempts": 10,
                  "BackoffRate": 3
                }
              ]
            },
            "log the details into db": {
              "Type": "Task",
              "Resource": "${LambdaFunctionLogInstanceDetailsInDynamoDB.Arn}",
              "InputPath": "$",
              "OutputPath": "$",
              "ResultPath": "$",
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.Unknown",
                    "Lambda.TooManyRequestsException",
                    "Lambda.SdkClientException",
                    "States.DataLimitExceeded"
                  ],
                  "IntervalSeconds": 10,
                  "MaxAttempts": 10,
                  "BackoffRate": 3
                }
              ],
              "TimeoutSeconds": 60,
              "End": true
            }
          }
        }      
          
  StateMachineScheduler:
    Type: 'AWS::StepFunctions::StateMachine' 
    Properties:
      Role: !GetAtt 'StepFunctionAccessEnableRole.Arn'
      DefinitionString: !Sub |
        {
          "Comment": "AWS Step Functions",
          "StartAt": "scheduling",
          "States": {
          "scheduling": {
            "Type": "Task",
            "Resource": "${LambdaFunctionJobScheduler.Arn}",
            "InputPath": "$",
            "OutputPath": "$",
            "ResultPath": "$",
            "TimeoutSeconds": 60,
            "Next": "push workload into pcluster",
            "Retry": [
              {
                "ErrorEquals": [
                  "Lambda.Unknown",
                  "Lambda.ServiceException",
                  "Lambda.TooManyRequestsException",
                  "ProvisionedThroughputExceededException",
                  "States.DataLimitExceeded"
                ],
                "IntervalSeconds": 10,
                "MaxAttempts": 10,
                "BackoffRate": 3
              }
            ]
          },
          "push workload into pcluster": {
            "Type": "Task",
            "Resource": "${LambdaFunctionPushWorkload.Arn}",
            "InputPath": "$",
            "OutputPath": "$",
            "ResultPath": "$",
            "TimeoutSeconds": 60,
            "Next": "give permissions",
              "Retry": [
              {
                "ErrorEquals": [
                  "Lambda.Unknown",
                  "Lambda.TooManyRequestsException",
                  "States.DataLimitExceeded"
                ],
                "IntervalSeconds": 10,
                "MaxAttempts": 10,
                "BackoffRate": 3
              }
              ]
          },
          "give permissions": 
          {
            "Type": "Task",
            "Resource": "${LambdaFunctionWorkloadCHMOD.Arn}",
            "InputPath": "$",
            "OutputPath": "$",
            "ResultPath": "$",
            "TimeoutSeconds": 60,
            "Next": "start workload launcher script ",
            "Retry": [
            {
              "ErrorEquals": [
                "Lambda.Unknown",
                "Lambda.TooManyRequestsException",
                "States.DataLimitExceeded"
              ],
              "IntervalSeconds": 10,
              "MaxAttempts": 10,
              "BackoffRate": 3
            }
            ]
          },
          "start workload launcher script ": 
          {
            "Type": "Task",
            "Resource": "${LambdaFunctionWorkloadCHMOD.Arn}",
            "InputPath": "$",
            "OutputPath": "$",
            "ResultPath": "$",
            "TimeoutSeconds": 60,
            "End": true,
            "Retry": [
            {
              "ErrorEquals": [
                "Lambda.Unknown",
                "Lambda.TooManyRequestsException",
                "States.DataLimitExceeded"
              ],
              "IntervalSeconds": 10,
              "MaxAttempts": 10,
              "BackoffRate": 3
            }
            ]
          }
        }
  
  LambdaFunctionJobScheduler:
    Type: AWS::Lambda::Function
    Properties:
      Description: 'This Lambda function is responsible for scheduling of Jobs'
      Handler: LambdaFunctionJobScheduler.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-job-scheduling/LambdaFunctionJobScheduler.py'
      MemorySize: 128
      Timeout: 120
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      Environment:
        Variables:
          ENV_CLUSTER_TABLE_NAME: hsmc_clusters
          ENV_JOB_STATUS_TABLE_NAME: hsmc_job_status
      ReservedConcurrentExecutions: 1
      FunctionName: !Sub 'LambdaFunctionJobScheduler-${DeployType}'
  
  LambdaFunctionPushWorkload:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionPushWorkload.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-job-scheduling/LambdaFunctionPushWorkload.py'
      Description: 'Lambda function to push workload into Parallel Cluster Master.  Uses SSM'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionPushWorkload-${DeployType}'

  LambdaFunctionWorkloadCHMOD:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionWorkloadCHMOD.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-job-scheduling/LambdaFunctionWorkloadCHMOD.py'
      Description: 'Lambda Function to run chmod on the workload.tgz which is present in Parallel Cluster Master. Uses SSM'
      MemorySize: 128
      Timeout: 120
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionWorkloadCHMOD-${DeployType}'

  LambdaFunctionWorkloadLauncher:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionWorkloadLauncher.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-job-scheduling/LambdaFunctionWorkloadLauncher.py'
      Description: 'Lambda Function to invoke Launcher Script in Parallel Cluster Master. Uses SSM'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionWorkloadLauncher-${DeployType}'
  
  LambdaFunctionInstanceSelection:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionInstanceSelection.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-pcluster-engine/LambdaFunctionInstanceSelection.py'
      Description: 'Lambda Function to appropiately select the instance'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionInstanceSelection-${DeployType}' 
  
  LambdaFunctionPclusterConfigInstantiate:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionPclusterConfigInstantiate.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-pcluster-engine/LambdaFunctionPclusterConfigInstantiate.py'
      Description: 'Lambda Function to instantiate the pcluster config from input json and defaults.'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionInstanceSelection-${DeployType}'
      Environment:
        Variables:
          ENV_COMPUTE_SUBNETS: subnet-02f23b848a57c997c subnet-009533dfc7f1b8822
          ENV_COMPUTE_SUBNETS_VPC2: subnet-05ef5190811add3ec subnet-0d22d39e62448e6ec
          ENV_MASTER_SUBNETS: subnet-0010e9d7052535060 subnet-05a95d03f9d2e3d87
          ENV_MASTER_SUBNETS_VPC2: subnet-0f53297dee0ceae1c subnet-0fafe3a3c2aecd26d
          ENV_PROXY_SERVER: >-
            'http://ProxyLoadBallancer-4062348da7a3ad2a.elb.us-west-2.amazonaws.com:3128'
          ENV_PROXY_SERVER_VPC2: >-
            'http://ProxyLoadBallancerVPC2-9e91024c11830d86.elb.us-west-2.amazonaws.com:3128'
          ENV_VPC2_ID: vpc-0e69be69b719bc5a4

  LambdaFunctionClusterCreation:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionClusterCreation.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-pcluster-engine/LambdaFunctionClusterCreation.py'
      Description: 'Lambda Function to invoke Launcher Script in Parallel Cluster Master. Uses SSM'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionClusterCreation-${DeployType}'
      VpcConfig:
        SecurityGroupIds:
          - sg-0dbed148ee1293020
        SubnetIds:
          - subnet-05a95d03f9d2e3d87
          - subnet-009533dfc7f1b8822
          - subnet-02f23b848a57c997c
          - subnet-0010e9d7052535060
          - subnet-06ae1a452fe129ac9
          - subnet-08dd8fdbc2fc95066
      Environment:
        Variables:
          ENV_SSM_INSTANCE_ID: i-07f1d82e6b2e3f60e

  LambdaFunctionClusterCreationStatus:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionClusterCreationStatus.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-pcluster-engine/LambdaFunctionClusterCreationStatus.py'
      Description: 'Lambda Function to check the status of the cluster in interest'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionClusterCreationStatus-${DeployType}'
      Layers:
        - 'arn:aws:lambda:us-west-2:078794018778:layer:pc270:2'

  LambdaFunctionMasterInstanceDetails:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionMasterInstanceDetails.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-pcluster-engine/LambdaFunctionMasterInstanceDetails.py'
      Description: 'Lambda Function to get Instance ID and IP Address of master instance'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionMasterInstanceDetails-${DeployType}' 

  LambdaFunctionLogInstanceDetailsInDynamoDB:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: LambdaFunctionLogInstanceDetailsInDynamoDB.lambda_handler
      Runtime: python3.8
      Code: 'src/lambda/sfn-pcluster-engine/LambdaFunctionLogInstanceDetailsInDynamoDB.py'
      Description: 'Lambda Function to appropiately select the instance'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LambdaServiceAccessEnableRole.Arn
      FunctionName: !Sub 'LambdaFunctionLogInstanceDetailsInDynamoDB-${DeployType}'
      Environment:
        Variables:
          ENV_CLUSTER_TABLE_NAME: hsmc_clusters
